Class-Widgets/Class-Widgets

menu.py
```
Traceback (most recent call last):
File "D:\Desktop\programming\Class-Widgets\exact_menu.py", line 35, in open_settings
settings = SettingsMenu()
File "D:\Desktop\programming\Class-Widgets\menu.py", line 367, in __init__
self.init_window()
~~~~~~~~~~~~~~~~^^
File "D:\Desktop\programming\Class-Widgets\menu.py", line 1869, in init_window
self.load_all_item()
~~~~~~~~~~~~~~~~~~^^
File "D:\Desktop\programming\Class-Widgets\menu.py", line 378, in load_all_item
self.setup_advance_interface()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "D:\Desktop\programming\Class-Widgets\menu.py", line 731, in setup_advance_interface
slider_scale_factor.setValue(float(conf.read_conf('General', 'scale')) * 100)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: setValue(self, …
```
=> fix(menu): 修复缩放滑块的值类型错误

exact_menu.py, main.py, menu.py, plugin_plaza.py
- 修复了：
- macOS: 失焦时不显示小组件和浮窗的问题
- macOS: 设置标题栏没有按钮的问题
- macOS: 设置、额外选项和插件广场在启动时不会自动焦点的问题
- 全平台: #217 遗落的部分
=> fix(macos): 修复了一些窗口问题

.github/workflows/build.yml, requirements.txt
把pyqt5-qt5的版本改为 `~=5.15.2`，这样可以在 Apple Silicon 的 Mac 上运行。
=> ci: 构建 macOS arm64 版本

main.py
p_Position is only set when the mouse press event is for a left click, thus it may be unavailable when the release event is for a right click.
Tested-by: xtex <xtex@aosc.io>
Signed-off-by: xtex <xtex@aosc.io>
已在 Linux (AOSC OS) 上测试。
=> fix: 修复右键悬浮窗时的错误

config/default_config.json, main.py, menu.py, view/menu/advance.ui
允许通过点击或触摸小组件方式控制小组件
若启用，单击小组件可显示或隐藏小组件，右键小组件可打开额外选项
若禁用，点击小组件等同于点击小组件后方的窗口
=> feat: 允许手动设置鼠标穿透

main.py
**问题修复** 
1. **边界值处理**
- 边距配置`max(0, value)`确保非负值
- 修复窗口位置计算异常
2. **动画状态管理**
- 执行动画时跳过数据更新逻辑（`if self.animating: return`）
- 优化窗口显示动画时长至400ms
---
**功能优化** 
1. **动画优化**
- 新增`sync_widget_animation`方法实现小部件与主组件动画同步
- 主组件添加形变动画方法`animate_expand`
- 加入弹出动画
2. **浮窗收起动画优化**
- 浮窗收拢时同步执行渐隐动画
- 动画目标位置改主组件坐标(上半部分);下部:主组件正下方屏幕外
- 动画时长按照屏幕位置自动计算
---   
**演示**
*修复*
https://github.com/user-attachments/assets/93a31c0a-7128-46e5-ac00-28bba240795d
==>
https://github.com/user-attachments/assets/7135bbbd-c28d-4f32-b314-a3a97723ad22
*动画*
https://github.com/user-attachments/assets/258a15d4-b700-497e-8bf8-cd6e38dff0b2
=> fix(widgets): 主组件的移动速度异常

main.py, tip_toast.py
- state=2（放学）时，无论toast.finish_class配置如何都会返回True
- 放学通知无法通过配置
---
clone #469 :通过显示测试(也不能说全是?)(休息段没法正常显示下课(我呃呃),,)
=> fix(tip_toast): 修正放学通知的条件判断逻辑

main.py, requirements.txt
- 添加 `get_process_name` 使用 `psutil` 获取进程信息
- 新增过滤进程：`explorer.exe`(无标题栏/Program Manager,桌面底状态), `shellexperiencehost`, `searchui` 
- 普通窗口:覆盖屏幕边界,窗口面积>=95%屏幕时返回全屏
- 修复 Win11_23H2 误判问题
- 检查句柄有效性
- 增加`psutil` ==> `requirements.txt`
~~由我给openai打工()~~
=> fix: 优化全屏和最大化检测逻辑

main.py, plugin_plaza.py
- 插件路径处理优化
- 布局分配逻辑
- 直接用 `os.path.normpath` 和 `os.path.join` 拼接路径,防止出现非正常的解析路径
- `QHBoxLayout` 和 `QVBoxLayout` 改为独立创建，避免重复分配
=> fix: 优化插件插件路径返回

main.py
在main.py中添加自定义主题监听逻辑，通过添加主题监听器on_theme_changed函数，在主题切换时调用mgr.clear_widgets()并重新初始化界面，解决了界面热重载的问题（似乎）
=> 修复#issue470

main.py
- 在获取天气数据失败时
- 将天气图标设置为未知状态（99.svg）
- 将温度显示设置为 '--°'
- 更新天气状态显示为 '未知'
- 修复获取失败时出现的None,错误的log
---
fix:
=> feat(weather): 天气组件错误显示

main.py
Clone #545 
- 根据节点序数和课程序数对timeline进行排序,防止误识别排序
=> fix: 单节点过多课程导致的显示错误

extra_menu.py, main.py
Reverts Class-Widgets/Class-Widgets#569
上游将修复。
This reverts commit https://github.com/Class-Widgets/Class-Widgets/commit/c440a9000dd4288afc372bddf81d5a12b2aa4112
=> revert: qfw 中 deregister 错误绑定造成的更改主题访问已删除元素

conf.py, menu.py, view/menu/advance.ui
close #614 
fix #586 
revert #587 
还有我把 advance.ui 的错误字段也带着改了
=> fix: CalendarPicker 获取日期方式错误导致的无法解析日期

README.md
=> doc: README 中社区开发者名单非团队人员无法访问

requirements.txt
This reverts commit af72c69ee0f9a0dd6c6170a03152c6ee3cebe07f.
```
ERROR: Could not find a version that satisfies the requirement urllib3==2.5.0 (from versions: 0.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1.2.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.7.1, 1.8, 1.8.2, 1.8.3, 1.9, 1.9.1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11, 1.12, 1.13, 1.13.1, 1.14, 1.15, 1.15.1, 1.16, 1.17, 1.18, 1.18.1, 1.19, 1.19.1, 1.20, 1.21, 1.21.1, 1.22, 1.23, 1.24, 1.24.1, 1.24.2, 1.24.3, 1.25.2, 1.25.3, 1.25.4, 1.25.5, 1.25.6, 1.25.7, 1.25.8, 1.25.9, 1.25.10, 1.25.11, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.26.5, 1.26.6, 1.26.7, 1.26.8, 1.26.9, 1.26.10, 1.26.11, 1.26.12, 1.26.13, 1.26.14, 1.26.15, 1.26.16, 1.26.17, 1.26.18, 1.26.19, 1.26.20, 2.0.0a1, 2.0.0a2, 2.0.0a3, 2.0.0a4, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, …
```
=> revert: "chore(deps): bump urllib3 from 2.2.3 to 2.5.0"

main.py
Potential fix for [https://github.com/Class-Widgets/Class-Widgets/security/code-scanning/52](https://github.com/Class-Widgets/Class-Widgets/security/code-scanning/52)
To fix the issue, the call to `get_widget_pos` on line 1698 should be updated to include the `cnt` argument. Since the `cnt` parameter is optional and defaults to `None`, the fix can either explicitly pass `None` or provide a meaningful value based on the context of the code. If the `cnt` value is not readily available, passing `None` ensures the method behaves as intended without introducing ambiguity.
The fix involves:
1. Updating the call to `parent.get_widget_pos(self.path)` to include the `cnt` argument.
2. Ensuring that the value passed for `cnt` aligns with the intended logic of the code.
---
_Suggested fixes powered …
=> chore: "Potential fix for code scanning alert no. 52: Wrong number of arguments in a call"

menu.py
当 config_center 里写了一个不存在的主题时会出事。
=> fix: i18n 主题目录获取不正确

weather.py
Potential fix for [https://github.com/Class-Widgets/Class-Widgets/security/code-scanning/13](https://github.com/Class-Widgets/Class-Widgets/security/code-scanning/13)
To fix the issue, we need to ensure that a valid exception is always raised on line 58. If `last_exception` is `None`, it means no exception was caught during the retries, which is unexpected. In such cases, we can raise a generic exception with a descriptive error message. This ensures that the `raise` statement always raises a valid exception object.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> chore: Illegal raise (fixed)

generate_speech.py
Potential fix for [https://github.com/Class-Widgets/Class-Widgets/security/code-scanning/134](https://github.com/Class-Widgets/Class-Widgets/security/code-scanning/134)
To fix the issue, we will remove the assignment of the return value of `stop_audio()` to the variable `success`. Instead, we will call `stop_audio()` directly without assigning its return value. Additionally, we will remove any subsequent use of the `success` variable, as it is unnecessary and misleading.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 134: Use of the return value of a procedure

main.py
天气预警字数飘忽不定，新增了更完善的显示适应规则
修改前：
修改后：
目前遇见最离谱的 8 字预警信息的也能展示全：
不过就是要把预警俩字去了
_哎不是 sb Windows 剪贴板里的图片怎么自动把透明通道干没_
=> chore: 完善天气预警的自适应显示
