- weather_db.py
其实是个小BUG（GBK→UTF-8）
修改过后目前在本人的环境里一切正常……
> 修复因解码问题导致的无法启动

- .gitignore
- .idea/dataSources.xml
- config/data/weather_api.json
- weather_db.py
> feat(weather): add amap_weather

- config/data/weather_api.json
- weather_db.py
> fix(weather): fixed amap_weather

- .gitignore
- config/data/qq_weather_status.json
- config/data/weather_api.json
- menu-custom.ui
- weather_db.py
> feat(weather): add qq_weather

- .github/ISSUE_TEMPLATE/BugReport.yml
- .github/ISSUE_TEMPLATE/FeatureRequest.yml
- menu-advance.ui
- menu-custom.ui
> chore: 改正说法，删除无用的模板部分

- .github/workflows/build.yml
- menu-schedule_edit.ui
- **ci:**
- 更新 Action
- 简化步骤
- 设置 Pyinstaller 参数
- **ui:**
- **课程表编辑** 将`下个星期`改为`下一天`
> improvement(ci, ui)

- menu.py
> fix: #143 apply timeline changes

- plugins/test/main.py
> fix: #161 test plugin

- .gitignore
- conf.py
- config.ini
- exact_menu.py
- list.py
- main.py
- menu.py
- network_thread.py
- plugin_plaza.py
- tip_toast.py
- weather_db.py
> refactor!: 使用绝对路径

- .github/workflows/build.yml
> fix(ci/non-macos): disable upload *.app

- .github/workflows/build.yml
在 Windows 构建时引入 numpy.core._multiarray_umath
fixed #191 #234
测试过，Windows 下通知没问题了，本来录了屏，传不上来了
> fix(ci): 在 Windows 构建时引入 numpy

- exact_menu.py
- list.py
- main.py
- menu.py
- network_thread.py
- plugin_plaza.py
- tip_toast.py
- weather_db.py
> refactor(improve): 在其他文件中应用 conf 定义的绝对路径

- .github/ISSUE_TEMPLATE/BugReport.yml
- .github/ISSUE_TEMPLATE/FeatureRequest.yml
- .github/workflows/similarity.yaml
Issue 相似性分析和模板修改，补一下我自己挖的坑。
包括 @Detritalw 在 #251 的更改，在此表示感谢。
以及，压缩合并。
> Issue 相似性分析和模板修改

- .github/ISSUE_TEMPLATE/BugReport.yml
- .github/ISSUE_TEMPLATE/FeatureRequest.yml
- .github/ISSUE_TEMPLATE/PluginsRequest.yml
- .github/ISSUE_TEMPLATE/config.yml
应该是`提交`Issue，而不是上传。  
打的时候没注意
> [!NOTE]
>
> 第 44 行
> 上传 → 提交
> 修正表述上两个错误的字

- config/default_config.json
- main.py
- menu-advance.ui
- menu.py
> feat: 自定义缩放

- .github/workflows/build.yml
> fix(ci): 从 view 添加 ui 文件

- main.py
- tip_toast.py
- 在 send_notification 函数中添加 duration 参数，默认为 2000 毫秒
- 更新 tip_toast 类构造函数，增加 duration 参数用于设置通知显示时长
- 修改 main 函数，支持传入 duration 参数自定义通知显示时长
> feat(notification): 增加通知显示时长参数

- main.py
- 为 update_widget_for_plugin 函数的参数添加默认值
- 优化了错误处理
> fix(main): 修复更新插件小组件时可能发生的错误

- .github/workflows/build.yml
> ci: Windows 构建使用 upx 压缩

- .github/workflows/build.yml
> ci: 上传整个文件夹

- README.md
> Add：README文件中中文路径警告

- main.py
- 采用版本号判断 Windows 10 build 14393及以上支持深色模式，可自动判断
- 格式化代码 符合PEP 8规范，增强可读性
> fix(main): 修复Windows系统下主题颜色自动判断

- main.py
- requirements.linux.txt
- requirements.txt
- 修复了更新插件小组件时可能出现的 NoneType 错误
- 优化了代码结构，补全未导入的库
> fix(main): 修复更新插件小组件时的错误

- cses_mgr.py
> fix(cses): `start_time` 转为 string

- cses_mgr.py
> fix(cese/decode): yaml 将时间解析成 int

- requirements.txt
> build: 设置 pyttsx3 版本为 2.71

- main.py
- 增加模糊匹配排除包含"Overlay","Snipping","SideBar"字样的进程
- 增加排除`SnippingTool`(系统截图工具)
---
> feat: 增加模糊排除

- main.py
- 我怎么给update_timer删了(?
#444 
---
---
> fix(FloatingWidget): 修复浮窗不显示信息

- main.py
> fix: 修复设定自动隐藏后手动隐藏出现的问题

- main.py
- utils.py
> chore: 增加（预留？）优雅的 stop()

- main.py
哥们好歹看一眼啊（
self.close （不带括号）忘删了）
@RinLit-233-shiroko
> fix: #476 多余代码

- main.py
---
- 浮窗保存逻辑
- 防止出现部分情况保存的浮窗位置乱标
---
- 多显示器位置
- 动态适配动画位置
> fix(widget): 优化浮窗保存逻辑

- cses_mgr.py
> fix: 导出CSES课表崩溃

- main.py
- network_thread.py
- utils.py
- `main.py`: add.等待线程完全终止
- `network_thread.py`add.运行状态`_running`
- 退出时进行子对象清理
- 顺便兼容了下ctrl+c(
----
- 也许能解决这种玄学问题(
> fix: 进程关闭流程优化

- main.py
> fix(openProgressDialog): 修复缺失的save_position

- menu.py
> fix(menu): 打开错误的配置目录

- menu.py
> fix: 插件未启用时显示设置按钮

- config/default_config.json
- menu.py
- play_audio.py
- requirements.txt
- tip_toast.py
- view/menu/sound.ui
- ### **灵动通知功能**：其他应用音量动态调节
https://github.com/user-attachments/assets/e575f8e4-42f1-4752-94c5-d7bd076b5152
---
| **注意**               | **出现情况**                     | **描述**                                                                 |
|--------------------------|----------------------------------|---------------------------------------------------------------------------------|
| **音频延迟**          | 灵动通知开启时               | 音量平滑调节后到播放存在延迟(其实再开一个线程就不会出现,but需要先降低其他应用音量) |
| **预加载音频**          |  /             | / |
---
- pycaw (Windows)
- pulsectl (Linux)
- subprocess (macOS)
> feat(play_audio): 灵动通知功能

- main.py
- 忘记commit了,修复[#547](https://github.com/Class-Widgets/Class-Widgets/pull/547)中的课间蒸发的问题
> fix: 修正get_start_time的排序逻辑 

- extra_menu.py
- main.py
> fix: 调休后未重新读取课表

- play_audio.py
> fix: 无声卡时报错

- main.py
> refactor: 窗口最大化检查

- main.py
> fix(DesktopWidget): 置底窗口争夺问题

- main.py
- view/menu/advance.ui
> refactor: 灵活隐藏逻辑

- ui/default/dark/widget-base.ui
- ui/default/dark/widget-floating.ui
- ui/default/widget-base.ui
- ui/default/widget-floating.ui
- ui/hoshino/dark/widget-base.ui
- ui/hoshino/widget-base.ui
- ui/minimize/widget-base.ui
- ui/shiroko/dark/widget-base.ui
- ui/shiroko/widget-base.ui
> fix: 插件小组件与原生小组件未对齐

- menu.py
- play_audio.py
- requirements.txt
- view/menu/sound.ui
Q:如何写出没有bug的代码?
A:不写
Close #571
> revert: 灵动通知

- tip_toast.py
> fix(tip_toast): 修复高DPI下的显示问题

- main.py
> fix: 时间段第一个活动缺失预备铃

- extra_menu.py
- main.py
影响范围:
设置页面，临时换课页面
错误表现:
RuntimeError: wrapped C/C++ object of type XXX has been deleted
> fix: qfw 中 deregister 错误绑定造成的更改主题访问已删除元素

- main.py
- 课程相关 :
- 下节课程 (Next_Lessons)
- 当前课程 (Current_Lessons)
- 当前周次 (Current_Week)
- 排除的课程 (Excluded_Lessons)
- 时间相关 :
- 当前时间 (Current_Time)
- 时间线数据 (Timeline_Data)
- 节点开始时间 (Parts_Start_Time)
- 节点类型 (Parts_Type)
- 时差偏移 (Time_Offset)
- 课程表相关 :
- 课表名称 (Schedule_Name)
- 加载课表数据 (Loaded_Data)
- 天气相关 :
- 天气图标 (Weather_Icon)
- 城市代码 (City)
- 通知相关 :
- 上次通知时间 (Last_Notify_Time)
- 系统相关 :
- 当前主题 (Theme)
---
> feat(PluginManager): 添加新变量字段

- extra_menu.py
- main.py
- play_audio.py
- plugin_plaza.py
- tip_toast.py
> chore: 兼容性的开关检查

- main.py
> fix: 宽容的获取下节课

- conf.py
- requirements.txt
> fix: 使用dateutil解析日期

- .github/workflows/build_pyinstaller.yml
> ci: 删除release

- main.py
- utils.py
close #66 
反复拉窗口置顶,统一计时器调整到0.1s
可能要等一会,浮窗置顶没弄
> fix: 更高窗口置顶等级

- main.py
- utils.py
https://github.com/user-attachments/assets/a235415e-a8ad-4038-b10a-9e30c3413c8e
Close #106
> feat: 实现跟随系统切换颜色模式

- menu.py
- plugin.py
> refactor(plugin): 规范化的插件删除流程

- main.py
> fix: 天气预警切换时的空值检查

- basic_dirs.py
Close #455
添加基础文件夹，一次性改那么多拼接字符串基本上是不可能完成的，就两百行代码的更改就能天天冲突（
Link: #414
> feat(basic_dirs): init

- main.py
- menu.py
- utils.py
> fix: 非初次启动时组件位置错位

- main.py
> refactor: 全屏和最大化窗口检查

- main.py
> fix: 特定课程不隐藏在全屏自动隐藏中不可用

- view/extra_menu.ui
适配触摸，（其实就是改了一下.ui），未引用新库，win11x6424H2测试通过
> fix: 换课菜单不适配触摸操控

- .github/workflows/build.yml
- .github/workflows/build_pyinstaller.yml
- conf.py
- config/default_config.json
- cses_mgr.py
- extra_menu.py
- file.py
- list_.py
- main.py
- menu.py
- network_thread.py
- view/menu/about.ui
> feat: 可跟踪的版本信息管理

- main.py
> fix: 窗口最大化隐藏时默认开启鼠标穿透

- config/default_config.json
- main.py
- menu.py
- utils.py
- view/menu/custom.ui
> feat: 允许控制 自定义小组件“更多活动” 显示课程数 （1/多）

- menu.py
- view/menu/timeline_edit.ui
> feat: 支持编辑节点开始时间

- data_model.py
> feat(data_model): support cses & cw schedule

- generate_speech.py
- main.py
- menu.py
- play_audio.py
- tip_toast.py
- view/menu/tts_settings.ui
> refactor: 重构TTS播放逻辑

- .github/workflows/build.yml
- conf.py
- main.py
- menu.py
- utils.py
Reverts Class-Widgets/Class-Widgets#735
> Revert "chore: 支持linux开机自启 | ci: 回滚pyinstaller构建 | choice: 调整多实例判断为锁机制"

- README.md
- docs/readme/README.en_US.md
- docs/readme/README.ja.md
> docs(readme): 优化“安装和使用”描述(中,英文)

- file.py
- main.py
> chore: 不主动创建默认配置文件

- weather.py
> chore: 函数拆分 [skip ci]

- file.py
我草 i18n 加载太晚了
给老外先用着 新课表 - 1 吧
> fix: 切换语言后找不到课表

- main.py
一堆计时器互相打架各切各的，切换时快时慢
另外加了预警信息去重，有时候会莫名收到一样的预警信息，一个预警闪两三遍装可爱
> chore(weather): 合并天气组件定时器

- config/default_config.json
- main.py
- menu.py
- view/menu/custom.ui
- weather.py
> feat(weather): 自定义气象预警排除

- extra_menu.py
- list_.py
- main.py
- menu.py
- tip_toast.py
- utils.py
- view/menu/advance.ui
_**reopen: [PR#800](https://github.com/Class-Widgets/Class-Widgets/pull/800)**_
fix: 窗口状态热生效
feat: 次级底部窗口状态支持
fix: 窗口更新后渲染消失
fix: 置底鼠标事件不被处理
style: 调整鼠标穿透相关设置样式
chore: 合并处理样式
chore: 缩短置顶回调执行间隔
>Co-authored-by: ChatGPT-o3
合了我就睡大觉。
> fix: 窗口状态热生效

- .github/workflows/cache_clear.yml
> ci: cache_clear

- i18n_manager.py
- main.py
- ui/hoshino/i18n/zh_CN.ts
- ui/shiroko/i18n/zh_CN.ts
杳杳我真的想把你的 completed_i18n.json 啥了
主题 i18n 可以重构一下了 /qd
> fix: 翻译缺失时未回退导致的无限递归崩溃

- .pre-commit-config.yaml
> chore: pre-commit

- i18n/bo.ts
- i18n/en_US.ts
- i18n/ja_JP.ts
- i18n/ug.ts
- i18n/zh_CN.ts
- i18n/zh_HK.ts
- i18n/zh_SIMPLIFIED.ts
- plugin_plaza.py
Reverts Class-Widgets/Class-Widgets#881
哥们从翻译里改吧
> revert: "style(plugin_plaza): 优化时间标签格式"

- data/completed_i18n.json
- data_model.py
- main.py
- ui/default/theme.json
- ui/hoshino/theme.json
- ui/minimize/theme.json
- ui/shiroko/theme.json
> fix: 使用小尺寸主题时移动位置错误

- Scripts/buildOSX.sh
- Scripts/buildWin.bat
> [!IMPORTANT]
> 请确保您的 PR 满足以下要求, 谢谢！
>
> - **避免 Merge 提交:** 尽可能使用 **Rebase** 操作
> - **使用描述性标题:** 描述改动内容, 避免直接使用 Issue 编号。
> - **在正文中引用相关 Issue:** 例如：`close #XXX` 或 `fix #XXX`, 确保相关 Issue 可被关闭
> - **(若有) UI 更改:** 请添加一张或多张截图描述
> - **详细要求参考:** [贡献代码](https://github.com/Class-Widgets/Class-Widgets/blob/main/.github/CONTRIBUTING.md#%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81)
>
> 最后, 请将此模板文本替换为更改描述和必要时的其他上下文信息
> Release 1.2.0.1

- view/menu/about.ui
- view/menu/advance.ui
- view/menu/configs.ui
- view/menu/countdown_custom_edit.ui
- view/menu/custom.ui
- view/menu/help.ui
- view/menu/plugin_mgr.ui
- view/menu/preview.ui
- view/menu/schedule_db_edit.ui
- view/menu/schedule_edit.ui
- view/menu/sound.ui
- view/menu/subject.ui
- view/menu/timeline_edit.ui
- view/menu/tts_settings.ui
- view/menu/weather.ui
> fix: 设置窗口最小高度过大

- main.py
- menu.py
- ui/default/dark/widget-weather.ui
- ui/default/widget-weather.ui
- ui/hoshino/dark/widget-weather.ui
- ui/hoshino/widget-weather.ui
- ui/minimize/dark/widget-weather.ui
- ui/minimize/widget-weather.ui
- ui/shiroko/dark/widget-weather.ui
- ui/shiroko/widget-weather.ui
- utils.py
- view/menu/weather.ui
- view/menu/weather_alert_card.ui
- view/menu/weather_alert_msgbox.ui
> chore: 将svg渲染到IconWidget

- main.py
- utils.py
- 弱引用管理
- 回调错误计数与退避
- QMutex线程安全
- 回调执行超时检查
- 惰性删除
> refactor: UnionUpdateTimer

- .github/workflows/build.yml
- main.py
- utils.py
> refactor(UnionUpdateTimer): 无锁并发

- extra_menu.py
- menu.py
- plugin_plaza.py
- utils.py
> chore: 优化基础窗口尺寸计算

- extra_menu.py
- menu.py
- plugin_plaza.py
- utils.py
Reverts Class-Widgets/Class-Widgets#966
> Revert "chore: 优化基础窗口尺寸计算"
